version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Exposes MongoDB on the host's 27017 port
    environment:
      MONGO_INITDB_ROOT_USERNAME: abolade
      MONGO_INITDB_ROOT_PASSWORD: ayanniyi20
      MONGO_INITDB_DATABASE: product-service-db
    volumes:
      - ./data/product_db:/data/db  # Persistent storage for MongoDB
    networks:
      - product-service-network  # Custom network for service isolation
    restart: unless-stopped  # Ensures container restarts if it crashes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limits log size
        max-file: "3"    # Keeps only the last 3 log files
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s      # Check health every 30 seconds
      timeout: 10s       # Timeout for the health check
      retries: 3         # Retry 3 times before marking unhealthy
      start_period: 10s  # Wait 10 seconds before the first health check

networks:
  product-service-network:  # Custom bridge network for the service
    driver: bridge
