version: '3'
services:
  user_service_db:
    image: postgres:latest
    container_name: user
    environment:
      POSTGRES_USER: abolade
      POSTGRES_PASSWORD: ayanniyi20
      POSTGRES_DB: user_service_db
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data