version: '3.8'
services:
  inventory_service_db:
    image: postgres:latest
    container_name: inventory
    environment:
      POSTGRES_USER: abolade
      POSTGRES_PASSWORD: ayanniyi20
      POSTGRES_DB: inventory_service_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
